### ISSUE TITLE
Unable to install (make)

### ISSUE THREAD

**Issue by enjoysmath** [ianh/owl#10] opened 2018-09-11 11:00 UTC
```
>make
cc -O3 -std=c11 -pedantic -Wall -Wno-missing-braces -Wno-overlength-strings -DNO
T_UNIX  -o owl src/*.c
cc: error: src/*.c: Invalid argument
cc: fatal error: no input files
compilation terminated.
make: *** [owl] Error 1
```

What build tools do I need to get this to work?

**Comment by ianh** [comment] 2018-09-11 16:49
Thanks for reporting this.  What `cc` do you have installed?  It looks like we're relying on `cc` to expand `src/*.c`, which isn't portable.

**Comment by ianh** [comment] 2018-09-11 16:52
Never mind, ignore that last comment.  I tested this, and `make` should be using the shell to expand its arguments.  Can you run `make sysinfo` and `sh --version` and paste the results here?

**Comment by ianh** [comment] 2018-09-11 23:51
Thanks, that's helpful.  I tried installing Haskell Platform 8.2.1 to reproduce this build environment, but it doesn't seem to include `make`.  Do you remember how you installed `make`?  Does `make --version` say anything?

**Comment by enjoysmath** [comment] 2018-09-12 00:14
C:\MyProjects\___MECHANIKOS\GPUCloudDeepLearningResearch>where make
> C:\D\dmd2\windows\bin\make.exe
> C:\MyProjects\___MECHANIKOS\GPUCloudDeepLearningResearch>


It's part of DMD2 installation (D language)

I have so many build systems installed already like VS 2017 community.

Let me know which one to add to the pile.

Thanks.

-EnjoysMath

**Comment by ianh** [comment] 2018-09-12 00:55
It looks like the best way is to install [MSYS2](http://www.msys2.org/), which provides its own environment.  Then you can run:

```console
$ pacman -S git gcc make
$ git clone https://github.com/ianh/owl.git
$ cd owl
$ make
```

**Comment by mqudsi** [comment] 2018-09-28 05:13
If you're on Windows 10, nothing is easier than just enabling/installing WSL from the Windows Store.

**Comment by ianh** [comment] 2018-11-08 11:47
I've been testing in MSYS2 successfully for a while, so I'm going to close this.  Feel free to open a new issue if it isn't working for you or if you have any other questions.

**Closed by ianh** 2018-11-08 11:47 UTC
